# dpp.vim core plugins
[[plugins]]
repo = 'Shougo/dpp.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'Shougo/denops.vim'

# UI基本プラグイン（テスト用に最小限）
[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
